version: "3.2"

x-environment-common: &environment-common
  CLICKHOUSE_USER: clickhouse
  CLICKHOUSE_PASSWORD: clickhouse
  CLICKHOUSE_DB: clickhouse

  CLICKHOUSE_DSN: clickhouse+asynch://clickhouse:clickhouse@clickhouse:8123/clickhouse

x-build-common: &build-common
  build:
    context: ./
    dockerfile: Dockerfile
  deploy:
    restart_policy:
      condition: on-failure
      delay: 5s
      max_attempts: 3
      window: 5s
  networks:
    - hand-of-midas-tier

services:

  clickhouse:
    image: clickhouse/clickhouse-server:23.1-alpine
    environment:
      <<: *environment-common
      CLICKHOUSE_HOST: 0.0.0.0
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    ports:
      - '8123:8123'
      - '9000:9000'
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://0.0.0.0:8123/ping || exit 1
    restart: always
    networks:
      - hand-of-midas-tier

  clickhouse-migrations:
    <<: *build-common
    environment:
      <<: *environment-common
      CLICKHOUSE_HOST: clickhouse
    command: bash -c "houseplant init && houseplant migrate:up"
    depends_on:
      clickhouse:
        condition: service_healthy

  binance-spot-candlesticks-dag:
    <<: *build-common
    environment:
      <<: *environment-common
      BINANCE_SECTION_NAME: SPOT

      TICKER: BTCUSDT
      INTERVAL: 4h
    command: python3 src/entrypoints/binance_candlesticks_base.py
    depends_on:
      clickhouse-migrations:
        condition: service_completed_successfully
    restart: always

networks:
  hand-of-midas-tier: