name: pytest CI-pipeline

on:
  pull_request:
    branches:
      - master
      - dev

jobs:

  pytest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install poetry
        run: pip3 install poetry==1.7.1

      - name: Install dependencies
        run: poetry install -vvv --no-interaction --no-root

      - name: Pytest run
        run: pytest tests/
